### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [raydelto/exam_engine#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/raydelto/util/PasswordUtil.java: Line number => 10: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/org/raydelto/util/PasswordUtil.java: Line number => 12: API name => MessageDigest:<BR>

**Comment by raydelto** [comment]
Thanks for pointing it out.  It has now been changed to SHA-512.
